apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-sentinel
  labels:
    app: redis
    role: sentinel
spec:
  serviceName: redis-sentinel
  replicas: 3  # Sentinel은 홀수 개 권장 (쿼럼을 위해)
  selector:
    matchLabels:
      app: redis
      role: sentinel
  template:
    metadata:
      labels:
        app: redis
        role: sentinel
    spec:
      # Sentinel 초기화 컨테이너 (master IP 자동 검색)
      initContainers:
      - name: init-sentinel
        # image: redis:7.2.7-alpine3.22 # 가장 보편화된 안정적인 버전
        image : redis:8.4.0-alpine3.22 # 최신버전
        command:
        - sh
        - -c
        - |
          # Redis Master IP를 Sentinel 설정에 업데이트
          cp /tmp/sentinel.conf /etc/redis/sentinel.conf
          sed -i "s/redis-master/redis-master-0.redis-master.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local/g" /etc/redis/sentinel.conf
        volumeMounts:
        - name: redis-config
          mountPath: /tmp
        - name: sentinel-config
          mountPath: /etc/redis
      containers:
      - name: sentinel
        image : redis:8.4.0-alpine3.22
        ports:
        - containerPort: 26379
          name: sentinel
        command:
        - redis-sentinel
        args:
        - /etc/redis/sentinel.conf
        volumeMounts:
        - name: sentinel-config
          mountPath: /etc/redis
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "100m"
        livenessProbe:
          tcpSocket:
            port: 26379
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - redis-cli
            - -p
            - "26379"
            - ping
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: redis-config
        configMap:
          name: redis-config
      - name: sentinel-config
        emptyDir: {}
