# Headless Service: 각 Redis Pod에 고정 DNS 제공
# redis-0.redis-headless.payment-msa.svc.cluster.local
# redis-1.redis-headless.payment-msa.svc.cluster.local
# redis-2.redis-headless.payment-msa.svc.cluster.local
apiVersion: v1
kind: Service
metadata:
  name: redis-headless
  namespace: shop-msa
  labels:
    app: redis
spec:
  ports:
  - port: 6379
    targetPort: 6379
    name: redis
  clusterIP: None  # Headless Service
  selector:
    app: redis

---
# ClusterIP Service: 애플리케이션이 접근할 Service
# Sentinel이 현재 Master를 가리키도록 업데이트
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: shop-msa
  labels:
    app: redis
spec:
  ports:
  - port: 6379
    targetPort: 6379
    name: redis
  selector:
    app: redis
  type: ClusterIP