# Redis Sentinel StatefulSet: Master 모니터링 및 Failover
# 3개의 Sentinel이 Master를 감시
# Quorum 2: 2개 이상의 Sentinel이 동의하면 Failover 실행
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-sentinel
  namespace: shop-msa
spec:
  serviceName: redis-sentinel-headless
  replicas: 3  # Sentinel 3개 (홀수 권장)
  selector:
    matchLabels:
      app: redis-sentinel
  template:
    metadata:
      labels:
        app: redis-sentinel
    spec:
      # Init Container: Sentinel 설정 파일 생성
      initContainers:
      - name: config
        image: redis:8.4.0-alpine3.22
        command:
        - sh
        - -c
        - |
          # Sentinel 설정 생성
          cat > /etc/redis/sentinel.conf <<EOF
          bind 0.0.0.0
          port 26379
          dir /data
          
          # Master 모니터링 설정
          # mymaster: Master 그룹 이름
          # redis-0.redis-headless...: 초기 Master 주소
          # 6379: Redis 포트
          # 2: Quorum (과반수)
          sentinel monitor mymaster redis-0.redis-headless.payment-msa.svc.cluster.local 6379 2
          
          # Master가 5초간 응답 없으면 다운으로 판단
          sentinel down-after-milliseconds mymaster 5000
          
          # Failover 타임아웃 (10초)
          sentinel failover-timeout mymaster 10000
          
          # Failover 시 동시에 재구성할 Replica 수
          sentinel parallel-syncs mymaster 1
          
          # Sentinel 자신의 IP 알림 (Pod DNS)
          sentinel announce-ip \${HOSTNAME}.redis-sentinel-headless.payment-msa.svc.cluster.local
          sentinel announce-port 26379
          EOF
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
        - name: sentinel-config
          mountPath: /etc/redis
      
      containers:
      - name: sentinel
        image: redis:8.4.0-alpine3.22
        ports:
        - containerPort: 26379
          name: sentinel
        command:
        - redis-sentinel
        - /etc/redis/sentinel.conf
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        volumeMounts:
        - name: sentinel-data
          mountPath: /data
        - name: sentinel-config
          mountPath: /etc/redis
        # Liveness Probe: Sentinel이 응답하는지 확인
        livenessProbe:
          tcpSocket:
            port: 26379
          initialDelaySeconds: 30
          periodSeconds: 10
        # Readiness Probe: Sentinel 준비 완료 확인
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - redis-cli -p 26379 ping
          initialDelaySeconds: 5
          periodSeconds: 5
      
      volumes:
      - name: sentinel-config
        emptyDir: {}
  
  volumeClaimTemplates:
  - metadata:
      name: sentinel-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 100Mi  # Sentinel은 작은 용량