# Headless Service: 각 Sentinel Pod에 고정 DNS
apiVersion: v1
kind: Service
metadata:
  name: redis-sentinel-headless
  namespace: shop-msa
  labels:
    app: redis-sentinel
spec:
  ports:
  - port: 26379
    targetPort: 26379
    name: sentinel
  clusterIP: None
  selector:
    app: redis-sentinel

---
# ClusterIP Service: 애플리케이션이 Sentinel에 접근
apiVersion: v1
kind: Service
metadata:
  name: redis-sentinel-service
  namespace: shop-msa
  labels:
    app: redis-sentinel
spec:
  ports:
  - port: 26379
    targetPort: 26379
    name: sentinel
  selector:
    app: redis-sentinel
  type: ClusterIP